service: y2123-api
app: core
org: shankqr
frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-domain-manager
custom:
  profiles:
    dev: default
    prod: prodProfile
  domain:
    dev: dev-api.y2123.io
    prod: api.y2123.io
  cert:
    dev: "dev-api.y2123.io"
    prod: "*.y2123.io"
  customDomain:
    http:
      domainName: ${self:custom.domain.${opt:stage, 'dev'}}
      basePath: ""
      stage: ${self:provider.stage}
      certificateName: ${self:custom.cert.${opt:stage, 'dev'}}
      createRoute53Record: true
      enabled: true
      securityPolicy: tls_1_2
      endpointType: regional
      apiType: http

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage,'dev'}
  profile: ${self:custom.profiles.${sls:stage}}
  httpApi:
    cors: true
  environment:
    METADATA_TABLE: "${self:provider.stage}-metadata"
    CLANS_METADATA_TABLE: "${self:provider.stage}-clans-metadata"

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:BatchGetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
            - "secretsmanager:GetSecretValue"
          Resource:
            - "*"

functions:
  getAsset:
    handler: src/asset.handler
    events:
      - httpApi:
          path: /asset
          method: get
  getAssetClans:
    handler: src/asset-clans.handler
    events:
      - httpApi:
          path: /asset-clans
          method: get
  getClan:
    handler: src/clan.handler
    events:
      - httpApi:
          path: /clan
          method: get
  getAccount:
    handler: src/account.handler
    events:
      - httpApi:
          path: /account
          method: get
  getClaim:
    handler: src/claim.handler
    events:
      - httpApi:
          path: /claim
          method: get