service: y2123-api
app: core
org: shankqr
frameworkVersion: "2"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-lift
custom:
  serverless-offline:
    httpPort: 3003     # sets port for endpoints when running sls offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
            - 'secretsmanager:GetSecretValue'
          Resource:
            - '*'
            - { "Fn::GetAtt": ["ProductsTable", "Arn"] }

constructs:
  commands:
    type: queue
    worker:
      handler: src/handler.sender

functions:
  discordHello:
    handler: src/handler.discordHandler
    reservedConcurrency: 1
    events: 
      - httpApi:
          path: /discord
          method: post
  hello:
    handler: src/handler.hello
    reservedConcurrency: 1
    events:
      - httpApi:
          path: /hello
          method: get
  discordEndpoint:
    handler: src/handler.endpoint
    reservedConcurrency: 1
    events:
      - httpApi:
          path: /discordEndpoint
          method: post
    environment:
      QUEUE_URL: ${construct:commands.queueUrl}
      
  createProduct:
    handler: src/handlers.createProduct
    events:
      - httpApi:
          path: /product
          method: post
  getProduct:
    handler: src/handlers.getProduct
    events:
      - httpApi:
          path: /product/{id}
          method: get
  updateProduct:
    handler: src/handlers.updateProduct
    events:
      - httpApi:
          path: /product/{id}
          method: put
  deleteProduct:
    handler: src/handlers.deleteProduct
    events:
      - httpApi:
          path: /product/{id}
          method: delete
  listProduct:
    handler: src/handlers.listProduct
    events:
      - httpApi:
          path: /products
          method: get

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: productID
            AttributeType: S
        KeySchema:
          - AttributeName: productID
            KeyType: HASH
